### ISSUE TITLE
"reveal bookmark in current line" hangs

### ISSUE THREAD

**Issue by zhourrr** [tommyme/vscode-bookmark-x#33]
I am using v0.2.14.

Originally, i had a bookmark at line 4 and saved it. The saved file records the line text and number. Not sure why the line number is 3, though.

![image](https://github.com/user-attachments/assets/e3cecc89-a04f-451e-b15a-992230538e16)

![image](https://github.com/user-attachments/assets/fd7f0f59-7aa2-4d09-a69d-8dd6069acc0e)

Now if I remove this bookmark and run "load all workspace state" to load from the saved json file, the bookmark is correctly pinned at line 4, as expected. But if I then immediately run "reveal bookmark in current line" on line 4, the operation hangs for a long time.

Interestingly, if after loading the bookmarks, I open the bookmarks in the sidebar and click on this bookmark, it successfully navigates to line 4. After doing this, running "reveal bookmark in current line" works without any issues. So i suspect navigating to this bookmark modified some internal states and fixes the issue.

<img width="763" alt="截屏2024-11-15 11 21 04" src="https://github.com/user-attachments/assets/6f73832a-c1a4-4f37-b067-aab6218b0237">

Above is the minimal reproduction step i found, which doesn't involve bookmark misplacement as I mentioned in issue #27 .

**Comment by tommyme** [comment]
- lines in document(starts from 1) is different with code(starts from 0)
- I can't reproduce with the instruction, later I'll send a gif.

**Comment by zhourrr** [comment]
https://github.com/user-attachments/assets/14a64abc-4e60-49e1-9ab9-0fce12c204bb

After i run "reveal" it didn't respond. Toggle bookmark also didn't respond. And the side bar seems to be in some loop.

**Comment by tommyme** [comment]
In my case, "reveal" pop up a message, but it didn't select the bookmark in tree view, and "Toggle bookmark" also didn't respond.

I think It's because before you click the "bookmark icon" on sidebar, the treeview won't render. There is some logic in it, and finally leads to error.

To avoid that, you can put "bmx View" in right side bar, or click it first.
![image](https://github.com/user-attachments/assets/dbf7bb3b-4ee1-4196-b087-0b770e34eab2)

More detailed reason may take some time to analyse.
